--use-gl=desktop
--force-dark-mode
--enable=features=UseOzonePlatform,WebUIDarkMode,VaapiVideoEncoder,VaapiVideoDecoder,CanvasOopRasterization
--ozone-platform=wayland
--enable-wayland-ime
--gtk-version=4
--disable-features=UseChromeOSDirectVideoDecoder
