# $wallpaper_dir = ~/Pictures/wallpapers/miku_vaperwave.png
# $wallpaper_dir = ~/Pictures/wallpapers/everl_summer_dark.jpg
# $wallpaper_dir = ~/Pictures/wallpapers/everl_summer_bright.jpg
# $wallpaper_dir = ~/Pictures/wallpapers/megumin_light.jpeg
 $wallpaper_dir = ~/Pictures/wallpapers/megumin_drink.jpeg
#$wallpaper_dir = ~/Pictures/wallpapers/dragon.png  
# $wallpaper_dir = ~/Pictures/wallpapers/Dynamic-Wallpapers/Dark/Beach-Dark.png
# $wallpaper_dir = ~/Pictures/wallpapers/anime_girl_red.png
reload = $wallpaper_dir 
wallpaper = , $wallpaper_dir
